# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sabrina/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sabrina)

$(call add-radio-file-sha1-checked,radio/bootloader.img,ea46bbdc87b4e1e042d18956a8db98d30075e9a2)

endif
