# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sabrina/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sabrina)

$(call add-radio-file-sha1-checked,radio/bootloader.img,7ae8b1c23f606b5940a16b17f75fb2f710b11862)

endif
