# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sabrina/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/sabrina

PRODUCT_COPY_FILES += \
    vendor/google/sabrina/proprietary/odm/etc/etc/bluetooth/bt_vendor.conf:$(TARGET_COPY_OUT_ODM)/etc/etc/bluetooth/bt_vendor.conf \
    vendor/google/sabrina/proprietary/odm/etc/firmware/firmware.le:$(TARGET_COPY_OUT_ODM)/etc/firmware/firmware.le \
    vendor/google/sabrina/proprietary/odm/etc/tvconfig/pq/pq.db:$(TARGET_COPY_OUT_ODM)/etc/tvconfig/pq/pq.db \
    vendor/google/sabrina/proprietary/odm/etc/tvconfig/pq/pq_default.ini:$(TARGET_COPY_OUT_ODM)/etc/tvconfig/pq/pq_default.ini \
    vendor/google/sabrina/proprietary/odm/lib/libHwAudio_dcvdec.so:$(TARGET_COPY_OUT_ODM)/lib/libHwAudio_dcvdec.so \
    vendor/google/sabrina/proprietary/odm/lib/libHwAudio_dtshd.so:$(TARGET_COPY_OUT_ODM)/lib/libHwAudio_dtshd.so \
    vendor/google/sabrina/proprietary/odm/lib/modules/dovi.ko:$(TARGET_COPY_OUT_ODM)/lib/modules/dovi.ko \
    vendor/google/sabrina/proprietary/product/etc/permissions/com.google.android.tv.remotecontrol.logging.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.tv.remotecontrol.logging.xml \
    vendor/google/sabrina/proprietary/product/etc/permissions/privapp-permissions-sabrina.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-sabrina.xml \
    vendor/google/sabrina/proprietary/product/etc/sysconfig/com.google.android.feature.FAST_PAIRING.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/com.google.android.feature.FAST_PAIRING.xml \
    vendor/google/sabrina/proprietary/system/bin/low_power_warning:$(TARGET_COPY_OUT_SYSTEM)/bin/low_power_warning \
    vendor/google/sabrina/proprietary/system/etc/init/low_power_warning.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/low_power_warning.rc \
    vendor/google/sabrina/proprietary/system_ext/etc/permissions/com.google.android.chromecast.chromecastservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.android.chromecast.chromecastservice.xml \
    vendor/google/sabrina/proprietary/system_ext/etc/permissions/droidlogic_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/droidlogic_permissions.xml \
    vendor/google/sabrina/proprietary/vendor/bin/device_renew_key.bin:$(TARGET_COPY_OUT_VENDOR)/bin/device_renew_key.bin \
    vendor/google/sabrina/proprietary/vendor/bin/generate_attestation_device_id:$(TARGET_COPY_OUT_VENDOR)/bin/generate_attestation_device_id \
    vendor/google/sabrina/proprietary/vendor/bin/hw/android.hardware.drm@1.0-service.castkey:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.0-service.castkey \
    vendor/google/sabrina/proprietary/vendor/bin/hw/android.hardware.drm@1.4-service.netflix:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.4-service.netflix \
    vendor/google/sabrina/proprietary/vendor/bin/hw/android.hardware.security.keymint-service.amlogic:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.security.keymint-service.amlogic \
    vendor/google/sabrina/proprietary/vendor/bin/key_inject:$(TARGET_COPY_OUT_VENDOR)/bin/key_inject \
    vendor/google/sabrina/proprietary/vendor/bin/led_control_service:$(TARGET_COPY_OUT_VENDOR)/bin/led_control_service \
    vendor/google/sabrina/proprietary/vendor/bin/performance_settings:$(TARGET_COPY_OUT_VENDOR)/bin/performance_settings \
    vendor/google/sabrina/proprietary/vendor/bin/tee_dec_hash:$(TARGET_COPY_OUT_VENDOR)/bin/tee_dec_hash \
    vendor/google/sabrina/proprietary/vendor/bin/tee_hdcp:$(TARGET_COPY_OUT_VENDOR)/bin/tee_hdcp \
    vendor/google/sabrina/proprietary/vendor/bin/tee_key_inject:$(TARGET_COPY_OUT_VENDOR)/bin/tee_key_inject \
    vendor/google/sabrina/proprietary/vendor/bin/tee_lock_rpmb:$(TARGET_COPY_OUT_VENDOR)/bin/tee_lock_rpmb \
    vendor/google/sabrina/proprietary/vendor/bin/tee_provision:$(TARGET_COPY_OUT_VENDOR)/bin/tee_provision \
    vendor/google/sabrina/proprietary/vendor/bin/tee_provision_password_hash:$(TARGET_COPY_OUT_VENDOR)/bin/tee_provision_password_hash \
    vendor/google/sabrina/proprietary/vendor/etc/cert-chain.crt:$(TARGET_COPY_OUT_VENDOR)/etc/cert-chain.crt \
    vendor/google/sabrina/proprietary/vendor/etc/init/chromecast-init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/chromecast-init.rc \
    vendor/google/sabrina/proprietary/vendor/etc/init/hw/init.amlogic.sku.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.amlogic.sku.rc \
    vendor/google/sabrina/proprietary/vendor/etc/init/hw/init.sabrina.product.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.sabrina.product.rc \
    vendor/google/sabrina/proprietary/vendor/etc/init/key_inject.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/key_inject.rc \
    vendor/google/sabrina/proprietary/vendor/etc/init/led_control_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/led_control_service.rc \
    vendor/google/sabrina/proprietary/vendor/etc/init/performance_settings.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/performance_settings.rc \
    vendor/google/sabrina/proprietary/vendor/etc/init/tee_hdcp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee_hdcp.rc \
    vendor/google/sabrina/proprietary/vendor/etc/nrdp_audio_platform_capabilities.json:$(TARGET_COPY_OUT_VENDOR)/etc/nrdp_audio_platform_capabilities.json \
    vendor/google/sabrina/proprietary/vendor/etc/nrdp_platform_capabilities.json:$(TARGET_COPY_OUT_VENDOR)/etc/nrdp_platform_capabilities.json \
    vendor/google/sabrina/proprietary/vendor/etc/permissions/droidlogic.software.core.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/droidlogic.software.core.xml \
    vendor/google/sabrina/proprietary/vendor/etc/permissions/nrdp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/nrdp.xml \
    vendor/google/sabrina/proprietary/vendor/lib/libcast_auth.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcast_auth.so \
    vendor/google/sabrina/proprietary/vendor/lib/libnetflixplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetflixplugin.so \
    vendor/google/sabrina/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/google/sabrina/proprietary/vendor/lib/libsecmem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecmem.so \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/2c1a33c0-44cc-11e5-bc3b-0002a5d5c51b.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/2c1a33c0-44cc-11e5-bc3b-0002a5d5c51b.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/526fc4fc-7ee6-4a12-96e3-83da9565bce8.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/526fc4fc-7ee6-4a12-96e3-83da9565bce8.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/8efb1e1c-37e5-4326-a5d6-8c33726c7d57.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/8efb1e1c-37e5-4326-a5d6-8c33726c7d57.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/93a424e2-5608-4413-84a858b16a064dce.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/93a424e2-5608-4413-84a858b16a064dce.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/9a04f079-9840-4286-ab92-e65be0885f95.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/9a04f079-9840-4286-ab92-e65be0885f95.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/af1ae3a4-888b-4e11-b4ab1c2b972d1c11.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/af1ae3a4-888b-4e11-b4ab1c2b972d1c11.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/d83c3c4a-9e8d-4e4e-ad309d40e137f689.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/d83c3c4a-9e8d-4e4e-ad309d40e137f689.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta \
    vendor/google/sabrina/proprietary/vendor/lib/teetz/ff2a4bea-ef6d-11e6-89ccd4ae52a7b3b3.ta:$(TARGET_COPY_OUT_VENDOR)/lib/teetz/ff2a4bea-ef6d-11e6-89ccd4ae52a7b3b3.ta

PRODUCT_PACKAGES += \
    RemotecontrolLogging \
    SuwCustomization \
    TVAxel \
    ChromecastService \
    droidlogic-res \
    droidlogic.software.core
PRODUCT_COPY_FILES += \
    vendor/google/sabrina/proprietary/vendor/bin/hdcp_tx22:$(TARGET_COPY_OUT_VENDOR)/bin/hdcp_tx22 \
    vendor/google/sabrina/proprietary/vendor/bin/hw/android.hardware.graphics.composer@2.4-service.droidlogic:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.graphics.composer@2.4-service.droidlogic \
    vendor/google/sabrina/proprietary/vendor/bin/systemcontrol:$(TARGET_COPY_OUT_VENDOR)/bin/systemcontrol \
    vendor/google/sabrina/proprietary/vendor/etc/init/android.hardware.graphics.composer@2.4-service.droidlogic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.4-service.droidlogic.rc \
    vendor/google/sabrina/proprietary/vendor/etc/init/systemcontrol.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/systemcontrol.rc \
    vendor/google/sabrina/proprietary/vendor/lib/android.hardware.graphics.composer@2.1-resources-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.graphics.composer@2.1-resources-vendor.so \
    vendor/google/sabrina/proprietary/vendor/lib/android.hardware.graphics.composer@2.2-resources-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.graphics.composer@2.2-resources-vendor.so \
    vendor/google/sabrina/proprietary/vendor/lib/hw/hwcomposer.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.amlogic.so \
    vendor/google/sabrina/proprietary/vendor/lib/libfbc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfbc.so \
    vendor/google/sabrina/proprietary/vendor/lib/libmeson_display_adapter_remote.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmeson_display_adapter_remote.so \
    vendor/google/sabrina/proprietary/vendor/lib/libmeson_display_service.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmeson_display_service.so \
    vendor/google/sabrina/proprietary/vendor/lib/libpqcontrol.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpqcontrol.so \
    vendor/google/sabrina/proprietary/vendor/lib/libsystemcontrolservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystemcontrolservice.so \
    vendor/google/sabrina/proprietary/vendor/lib/libvideotunnel.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvideotunnel.so \
    vendor/google/sabrina/proprietary/vendor/lib/vendor.amlogic.display.meson_display_ipc@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.display.meson_display_ipc@1.0.so \
    vendor/google/sabrina/proprietary/vendor/lib/vendor.amlogic.hardware.droidvold@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.droidvold@1.0.so \
    vendor/google/sabrina/proprietary/vendor/lib/vendor.amlogic.hardware.systemcontrol@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.systemcontrol@1.0.so \
    vendor/google/sabrina/proprietary/vendor/lib/vendor.amlogic.hardware.systemcontrol@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.systemcontrol@1.1.so \
    vendor/google/sabrina/proprietary/vendor/lib/vendor.amlogic.hardware.tvserver@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.tvserver@1.0.so

PRODUCT_PACKAGES += \
    android.hardware.graphics.composer@2.4-service.droidlogic
